[package]
name = "common-tracing"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[features]
console = ["console-subscriber"]

[dependencies] # In alphabetical order
backtrace = "0.3.64"
console-subscriber = { version = "0.1.3", optional = true }
once_cell = "1.10.0"
opentelemetry = { version = "0.17.0", default-features = false, features = ["trace", "rt-tokio"] }
opentelemetry-jaeger = { version = "0.16.0", features = ["rt-tokio"] }
tonic = "=0.6.2"
tracing = "0.1.32"
tracing-appender = "0.2.2"
tracing-bunyan-formatter = "0.3.2"
tracing-futures = { version = "0.2.5", features = ["futures-03"] }
tracing-log = "0.1.2"
tracing-opentelemetry = "0.17.2"
tracing-subscriber = { version = "0.3.10", features = ["env-filter", "fmt", "time", "local-time"] }

log = "0.4"
