[workspace]
members = [
    "utils",
    "common/tracing",
    "chunk_server",
    "catalogue_master",
    "catalogue_master/tests/chunk_handler_heartbeat",
    "catalogue_master/tests/chunk_handler_register",

    "examples/tracing-test",
]
